### ISSUE TITLE
Gem does not seem to work for specific url

### ISSUE THREAD

**Issue by rajofchennai** [alext/invalid_utf8_rejector#4]
URL:

```
http://localhost/cgi-bin/php5/cgin/php?%2D%64+%61%6C%75%6F%6E+%2D%64+%6D%6F%64+%2D%64+%73%75%68%6F%6E%3D%6F%6E+%2D%64+%75%6E%63%74%73%3D%22%22+%2D%64+%64%6E%65+%2D%64+%61%75%74%6F%5F%70%72%%74+%2D%64+%63%67%69%2E%66%6F%72%63%65%5F%72%65%64%69%72%65%63%74%3D%30+%2D%64+%74%5F%3D%30+%2D%64+%75%74+%2D%6E
```

This gem does not catch this url. 

```
An ArgumentError occurred in home#unknown_request:

  invalid %-encoding (%2D%64+%61%6C%75%6F%6E+%2D%64+%6D%6F%64+%2D%64+%73%75%68%6F%6E%3D%6F%6E+%2D%64+%75%6E%63%74%73%3D%22%22+%2D%64+%64%6E%65+%2D%64+%61%75%74%6F%5F%70%72%%74+%2D%64+%63%67%69%2E%66%6F%72%63%65%5F%72%65%64%69%72%65%63%74%3D%30+%2D%64+%74%5F%3D%30+%2D%64+%75%74+%2D%6E)
  /home/ubuntu/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/uri/common.rb:898:in `decode_www_form_component'


-------------------------------
Request:
-------------------------------

  * URL       : http://localhost:5080/cgi-bin/php5/cgin/php?%2D%64+%61%6C%75%6F%6E+%2D%64+%6D%6F%64+%2D%64+%73%75%68%6F%6E%3D%6F%6E+%2D%64+%75%6E%63%74%73%3D%22%22+%2D%64+%64%6E%65+%2D%64+%61%75%74%6F%5F%70%72%%74+%2D%64+%63%67%69%2E%66%6F%72%63%65%5F%72%65%64%69%72%65%63%74%3D%30+%2D%64+%74%5F%3D%30+%2D%64+%75%74+%2D%6E
  * IP address: 127.0.0.1
  * Parameters: {"format"=>:json, "controller"=>"home", "action"=>"unknown_request", "anything"=>"cgi-bin/php5/cgin/php"}
  * Rails root: /home/ubuntu/app_home/spaghetti_ruby_1.9/releases/20140122051848/sf
  * Timestamp : 2014-01-22 06:57:24 UTC
  * REMOTE_PORT                                    : 33935
  * REQUEST_METHOD                                 : GET
  * REQUEST_URI                                    : /cgi-bin/php5/cgin/php?%2D%64+%61%6C%75%6F%6E+%2D%64+%6D%6F%64+%2D%64+%73%75%68%6F%6E%3D%6F%6E+%2D%64+%75%6E%63%74%73%3D%22%22+%2D%64+%64%6E%65+%2D%64+%61%75%74%6F%5F%70%72%%74+%2D%64+%63%67%69%2E%66%6F%72%63%65%5F%72%65%64%69%72%65%63%74%3D%30+%2D%64+%74%5F%3D%30+%2D%64+%75%74+%2D%6E
  * SCGI                                           : 1
  * SCRIPT_NAME                                    :
  * SERVER_ADDR                                    : 127.0.0.1
  * SERVER_NAME                                    : localhost
  * SERVER_PORT                                    : 5080
  * SERVER_PROTOCOL                                : HTTP/1.1
  * SERVER_SOFTWARE                                : nginx/1.4.2
  * UNION_STATION_SUPPORT                          : false
  * action_controller.instance                     : #<HomeController:0xeed755c>
  * action_dispatch.backtrace_cleaner              : #<Rails::BacktraceCleaner:0xb6b9bc0>
  * action_dispatch.cookies                        : #<ActionDispatch::Cookies::CookieJar:0xeec0294>
  * action_dispatch.logger                         : #<Syslog::Logger:0xb8192e0>
  * action_dispatch.parameter_filter               : [:password, :status_arr, :feed, /RAW_POST_DATA/, /RAW_POST_DATA/]
  * action_dispatch.remote_ip                      : 127.0.0.1
  * action_dispatch.request.content_type           :
  * action_dispatch.request.parameters             : {"format"=>:json, "controller"=>"home", "action"=>"unknown_request", "anything"=>"cgi-bin/php5/cgin/php"}
  * action_dispatch.request.path_parameters        : {:format=>:json, :controller=>"home", :action=>"unknown_request", :anything=>"cgi-bin/php5/cgin/php"}
  * action_dispatch.request.query_parameters       : {}
  * action_dispatch.request.request_parameters     : {}
  * action_dispatch.request.unsigned_session_cookie: {}
  * action_dispatch.request_id                     : b02734025ef12fa3167a626735ecea0a
  * action_dispatch.routes                         : #<ActionDispatch::Routing::RouteSet:0xb6fd6a4>
  * action_dispatch.secret_token                   : e82cca3d2dab7fbd0f340ed5b9fe44e4356e2d02ed3a8483180b0302727170a260ca1d32ca68d053247af8d67beb737d51d6cf12a27da9ff3e94fa6c69216018
  * action_dispatch.show_detailed_exceptions       : false
  * action_dispatch.show_exceptions                : true
  * newrelic.agent_hooks_before_fired              : true
  * rack-cache.allow_reload                        : false
  * rack-cache.allow_revalidate                    : false
  * rack-cache.cache_key                           : Rack::Cache::Key
  * rack-cache.default_ttl                         : 0
  * rack-cache.entitystore                         : rails:/
  * rack-cache.ignore_headers                      : ["Set-Cookie"]
  * rack-cache.metastore                           : rails:/
  * rack-cache.private_headers                     : ["Authorization", "Cookie"]
  * rack-cache.storage                             : #<Rack::Cache::Storage:0xb838168>
  * rack-cache.use_native_ttl                      : false
  * rack-cache.verbose                             : false
  * rack.errors                                    : #<IO:0x9f91100>
  * rack.hijack                                    : #<Proc:0xeec3318@/home/ubuntu/.rvm/gems/ruby-2.0.0-p247@spaghetti/ruby/2.0.0/gems/passenger-enterprise-server-4.0.12/lib/phusion_passenger/rack/thread_handler_extension.rb:53 (lambda)>
  * rack.hijack?                                   : true
  * rack.input                                     : #<PhusionPassenger::Utils::TeeInput:0xeec35e8>
  * rack.multiprocess                              : true
  * rack.multithread                               : false
  * rack.request.cookie_hash                       : {}
  * rack.request.query_string                      : %2D%64+%61%6C%75%6F%6E+%2D%64+%6D%6F%64+%2D%64+%73%75%68%6F%6E%3D%6F%6E+%2D%64+%75%6E%63%74%73%3D%22%22+%2D%64+%64%6E%65+%2D%64+%61%75%74%6F%5F%70%72%%74+%2D%64+%63%67%69%2E%66%6F%72%63%65%5F%72%65%64%69%72%65%63%74%3D%30+%2D%64+%74%5F%3D%30+%2D%64+%75%74+%2D%6E
  * rack.run_once                                  : false
  * rack.session                                   : {}
  * rack.session.options                           : {:path=>"/", :domain=>nil, :expire_after=>nil, :secure=>false, :httponly=>true, :defer=>false, :renew=>false, :secret=>"3e9ad381aa70eeb912191b7f43f4e8112866853cec7e32acc060b8c52a76", :coder=>#<Rack::Session::Cookie::Base64::Marshal:0xd156050>, :id=>nil}
  * rack.url_scheme                                : http
  * rack.version                                   : [1, 2]

  * Process: 24912
  * Server : domU-12-31-39-15-29-9E

-------------------------------
Backtrace:
-------------------------------

  /home/ubuntu/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/uri/common.rb:898:in `decode_www_form_component'
  rack (1.4.5) lib/rack/utils.rb:41:in `unescape'
  rack (1.4.5) lib/rack/utils.rb:94:in `block (2 levels) in parse_nested_query'
  rack (1.4.5) lib/rack/utils.rb:94:in `map'
  rack (1.4.5) lib/rack/utils.rb:94:in `block in parse_nested_query'
  rack (1.4.5) lib/rack/utils.rb:93:in `each'
  rack (1.4.5) lib/rack/utils.rb:93:in `parse_nested_query'
  rack (1.4.5) lib/rack/request.rb:332:in `parse_query'
  actionpack (3.2.13) lib/action_dispatch/http/request.rb:275:in `parse_query'
  rack (1.4.5) lib/rack/request.rb:186:in `GET'
  actionpack (3.2.13) lib/action_dispatch/http/request.rb:231:in `GET'
  actionpack (3.2.13) lib/action_dispatch/http/parameters.rb:10:in `parameters'
  actionpack (3.2.13) lib/action_dispatch/http/filter_parameters.rb:31:in `filtered_parameters'
  newrelic_rpm (3.7.1.182) lib/new_relic/agent/instrumentation/rails3/action_controller.rb:37:in `process_action'
  actionpack (3.2.13) lib/abstract_controller/base.rb:121:in `process'
  actionpack (3.2.13) lib/abstract_controller/rendering.rb:45:in `process'
  actionpack (3.2.13) lib/action_controller/metal.rb:203:in `dispatch'
  actionpack (3.2.13) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  actionpack (3.2.13) lib/action_controller/metal.rb:246:in `block in action'
  actionpack (3.2.13) lib/action_dispatch/routing/route_set.rb:73:in `call'
  actionpack (3.2.13) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (3.2.13) lib/action_dispatch/routing/route_set.rb:36:in `call'
  journey (1.0.4) lib/journey/router.rb:68:in `block in call'
  journey (1.0.4) lib/journey/router.rb:56:in `each'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.13) lib/action_dispatch/routing/route_set.rb:612:in `call'
  newrelic_rpm (3.7.1.182) lib/new_relic/rack/error_collector.rb:50:in `call'
  newrelic_rpm (3.7.1.182) lib/new_relic/rack/error_collector.rb:50:in `call'
  newrelic_rpm (3.7.1.182) lib/new_relic/rack/agent_hooks.rb:28:in `call'
  newrelic_rpm (3.7.1.182) lib/new_relic/rack/browser_monitoring.rb:23:in `call'
  exception_notification (4.0.0) lib/exception_notification/rack.rb:28:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  rack (1.4.5) lib/rack/etag.rb:23:in `call'
  rack (1.4.5) lib/rack/conditionalget.rb:25:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/flash.rb:242:in `call'
  rack (1.4.5) lib/rack/session/abstract/id.rb:210:in `context'
  rack (1.4.5) lib/rack/session/abstract/id.rb:205:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/cookies.rb:341:in `call'
  activerecord (3.2.13) lib/active_record/query_cache.rb:64:in `call'
  activerecord (3.2.13) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  activesupport (3.2.13) lib/active_support/callbacks.rb:405:in `_run__102955364__call__446296188__callbacks'
  activesupport (3.2.13) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.13) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.13) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.13) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  rack (1.4.5) lib/rack/sendfile.rb:102:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.13) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.13) lib/rails/rack/logger.rb:18:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.5) lib/rack/runtime.rb:17:in `call'
  rack (1.4.5) lib/rack/lock.rb:15:in `call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
  rack-cache (1.2) lib/rack/cache/context.rb:143:in `pass'
  rack-cache (1.2) lib/rack/cache/context.rb:172:in `rescue in lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:168:in `lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
  app/middleware/batch_requests.rb:18:in `call'
  invalid_utf8_rejector (0.0.1) lib/invalid_utf8_rejector/middleware.rb:11:in `call'
  railties (3.2.13) lib/rails/engine.rb:479:in `call'
  railties (3.2.13) lib/rails/application.rb:223:in `call'
  railties (3.2.13) lib/rails/railtie/configurable.rb:30:in `method_missing'
  passenger-enterprise-server (4.0.12) lib/phusion_passenger/rack/thread_handler_extension.rb:61:in `process_request'
  passenger-enterprise-server (4.0.12) lib/phusion_passenger/request_handler/thread_handler.rb:126:in `accept_and_process_next_request'
  passenger-enterprise-server (4.0.12) lib/phusion_passenger/request_handler/thread_handler.rb:94:in `main_loop'
  passenger-enterprise-server (4.0.12) lib/phusion_passenger/request_handler.rb:456:in `block (3 levels) in start_threads'

```

As  you can see, The request passes through the invalid_utf8_rejector middleware but it does not catch the exception. I am not very sure if it is a problem with the gem. Just confirming.

**Comment by alext** [comment]
Hi, sorry this has sat for so long without a reply...

Strictly speaking, that request isn't an invalid UTF-8 sequence, it's just not been validly % encoded (there's a bare `%` near the middle - `%72%%74+`.

Having said that, it should be simple enough to catch within this gem, and it would prevent another case of invalid requests causing the app to blow up.

**Comment by alext** [comment]
Version 0.0.2 published which should now catch this sort of thing
